name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions: write-all


    steps:
      - uses: actions/poetry-semantic-release@v0
