name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  Test:
    runs-on: ubuntu-latest
    concurrency: release
    permissions: write-all

    steps:
      - uses: matteo4diani/poetry-semantic-release@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
